### PR TITLE
Merge code from releases via tarballs

### PR DESCRIPTION
**Pull request by blueyed**
- imported them based on the last commit on bitbucket (https://bitbucket.org/pytest-dev/regendoc/commits/5552b72bd7b98a3a5164c979e3f121d420ab35e1)
- then merged master into it, resolving conflicts

### CODE REVIEW

**Comment by nicoddemus** [comment]
Awesome, thanks a lot! 👍

**Review by nicoddemus — APPROVED** [review]

**Comment by blueyed** [comment]
@nicoddemus 
You're welcome - that was very nasty (even until realizing that releases and master are way off/different).

Cannot merge myself, but probably @RonnyPfannschmidt should take a quick look at least.

**Comment by blueyed** [comment]
Also here again a clear disadvantage of not having coverage reports - I've only checked that tests are passing.

And another sidenote: the formatting changes were really demotivating here also (unnecessary merge conflicts).

**Comment by RonnyPfannschmidt** [comment]
thanks for wading trough this minefield,

i believe the merge pain could have been avoided in part by using black and/or a more compatible merge

**Comment by blueyed** [comment]
> i believe the merge pain could have been avoided in part by using black and/or a more compatible merge

It wasn't too bad in my second attempt, and mainly due to renaming variables also.

Thanks for merging!

**Pull request merged**
